{% set name = "pixi-pycharm" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pavelzw/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5179254a3bc5474bb42cb2a4618078ba4b6cebf7b987b1ef665dd321a31bb21d

build:
  noarch: generic
  script:
    - mkdir -p $PREFIX/libexec
    - echo "#!$PREFIX/bin/python" > $PREFIX/libexec/conda
    - cat conda >> $PREFIX/libexec/conda
    - sed -i '2d' $PREFIX/libexec/conda
    - chmod +x $PREFIX/libexec/conda
  number: 0

requirements:
  build:
    - sed
  run:
    - __unix
    - python >=3.8

test:
  commands:
    - test -f $PREFIX/libexec/conda

about:
  home: https://github.com/pavelzw/pixi-pycharm
  summary: Conda shim for PyCharm that proxies pixi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/pavelzw/pixi-pycharm

extra:
  recipe-maintainers:
    - pavelzw
